-- 约饭发起人、报名审核与我的活动

ALTER TABLE meetup ADD COLUMN host_openid VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE meetup ADD COLUMN require_approval BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE meetup_member ADD COLUMN member_status VARCHAR(16) NOT NULL DEFAULT 'APPROVED';
ALTER TABLE meetup_member ADD COLUMN is_host BOOLEAN NOT NULL DEFAULT FALSE;
